In [ ]:
import numpy as np

In [19]:
one = np.array(range(20, 20+9))

print(*one[0:6])

20 21 22 23 24 25


In [51]:
two = np.array([[20,21,22],
                [23,24,25],
                [26,27,28]])
print(*[int(two[i][i]) for i in range(len(two))])

20 24 28


In [26]:
print(np.arange(20,20+10))
print(np.arange(20,20+10,2))
print(np.arange(20,20+10,3))

[20 21 22 23 24 25 26 27 28 29]
[20 22 24 26 28]
[20 23 26 29]


In [30]:
print(np.zeros_like(two))
print(np.ones_like(one))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1 1 1 1 1 1 1 1 1]


In [38]:
two = np.arange(20,20+36).reshape(9,4)
print(two, "\n")
two = np.arange(20,20+36).reshape(4,9)
print(two, "\n")
two = np.arange(20,20+36).reshape(3,12)
print(two, "\n")
two = np.arange(20,20+36).reshape(12,3)
print(two, "\n")

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]] 

[[20 21 22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44 45 46]
 [47 48 49 50 51 52 53 54 55]] 

[[20 21 22 23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41 42 43]
 [44 45 46 47 48 49 50 51 52 53 54 55]] 

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]
 [38 39 40]
 [41 42 43]
 [44 45 46]
 [47 48 49]
 [50 51 52]
 [53 54 55]] 



In [ ]:
ten = np.arange(20,20+10).reshape(2,5)
print(f"{type(ten)= }, \n{ten.dtype= }, \n{ten.size= }, \n{ten.shape= }, \n{ten.itemsize= }, \n{ten.ndim= }, \n{ten.nbytes= }")

type(ten)= <class 'numpy.ndarray'>, 
ten.dtype= dtype('int64'), 
ten.size= 10, 
ten.shape= (2, 5), 
ten.itemsize= 8, 
ten.ndim= 2, 
ten.nbytes= 80
